www/protected/models/Flats.php
<?php

class Flats extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	 
	public $buildingid;
	public $rooms;
	 
	public function tableName()
	{
		return '{{flats}}';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('planid,price', 'required'),
			array('planid,price', 'numerical', 'integerOnly'=>true,'min'=>1),
			array('entrances,floor', 'numerical', 'integerOnly'=>true),
			array('price','numerical'),
			array('hot', 'numerical'),			
			array('id, buildingid, rooms, price, hot, top', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(			
			'plan'=>array(self::BELONGS_TO, 'Plans', 'planid'),

		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'building'=>'Дом',
			'floor'=>'Этаж',
			'entrances'=>'Подьезд',
			'planid'=>'Планировка',
			'price' => 'Цена',
			'hot' => 'Скидка/акция',
		    'top' => 'Спецпредложение',
			'rooms'=>'Кол-во комнат',
			'buildingid'=>'Дом',			
		);
	}
		
	public function search()
    {
    	$criteria=new CDbCriteria;
       	
       	$criteria->with=array('plan'=>array('joinType'=>'INNER JOIN'));
		$criteria->together = true;
			
    
    	$criteria->compare('id',$this->id);
    	$criteria->compare('price',$this->price); 
    	$criteria->compare('floor',$this->floor); 
    	$criteria->compare('hot',$this->hot); 
    	$criteria->compare('rooms',$this->rooms);
		$criteria->compare('buildingid',$this->buildingid);
    	
		//$criteria->compare('price',$this->building);
    	/*
    	
    	$criteria->compare('s_total',$this->s_total);
    	$criteria->compare('s_living',$this->s_living);
    	$criteria->compare('s_kitchen',$this->s_kitchen);
    	$criteria->compare('s_loggia',$this->s_loggia);
    	$criteria->compare('loggia',$this->loggia);
    	$criteria->compare('buildingid',$this->buildingid);
    	
    	*/

    	   
    	return new CActiveDataProvider($this, array(
    			'criteria'=>$criteria,
    			//'sort'=>array('defaultOrder'=>'id ASC'),
    			'pagination'    => array('pageSize'  => 100)
    	));
    }
    
    public function getHotValues()
    {
        return array(
            array('id'=>0,'name'=>'Нет'),
            array('id'=>1,'name'=>'Скидка'),
            array('id'=>2,'name'=>'Спецпредложение'),
        );
    }

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return CatalogSection the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
}

www/protected/controllers/OrdersController.php
<?php

class OrdersController extends Controller
{

	public $layout='/layouts/default';
	
		
	public function actionCallMe() {	
		
		if(Yii::app()->request->isAjaxRequest) { 
			
			$this->renderPartial('callme',array(),false,true);
		}
		else
		{
			$this->render('callme');
		}
		
		
	}
	
	public function actionExcursions() { 
		
		if(Yii::app()->request->isAjaxRequest) {
			
			$this->renderPartial('excursions',array(),false,true);
		}
		else {
			
			$this->render('excursions');
		}
	}

	
	public function actionFlat($flatid) {
		
		$flat = Flats::model()->findByPK($flatid);	
		
		$flats = Flats::model()->with('plan')->findAllByAttributes(
				array(
						'planid'=>$flat->planid,
						'price'=>$flat->price
				));
		
		$floors = array();
		$flat = $flats[0];
		
		foreach ($flats as $flatrow) {
				
			$floors[$flatrow->id]=$flatrow->floor;			
				
			if ($flatid == $flatrow->id) {
				$flat = $flatrow;
			}
		}		
	
		if(Yii::app()->request->isAjaxRequest) {
				
			$this->renderPartial('flat',array('flat'=>$flat,'floors'=>$floors),false,true);
		}
		else {
				
			$this->render('flat',array('flat'=>$flat,'floors'=>$floors));
		}
	}
	
		
	
	public function actionIpoteka() {
		
		if(Yii::app()->request->isAjaxRequest) {
				
			$this->renderPartial('ipoteka',array(),false,true);
		
		} else {
				
			$this->render('ipoteka');
		}
	}
	
	
	public function actionTradein() {
		
		if(Yii::app()->request->isAjaxRequest) {
				
			$this->renderPartial('tradein',array(),false,true);
		
		} else {
				
			$this->render('tradein');
		}
	}

	public function actionAdd()
	{
				
		$model=new Orders;
		
		$model->attributes=$_POST['Orders'];
		
		if(isset($_POST['ajax']))
		{			
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
					
		
		
		if($model->validate() && $model->save())
		{
			$this->render('done');
		}
		
		
		
		
	}
	

	
}

www/protected/views/flats/export.php
<?php
header('Content-Description: File Transfer');
header("Content-Type: application/csv") ;
header("Content-Disposition: attachment; filename=".$_SERVER['HTTP_HOST'].".csv");
header("Pragma: no-cache");
header("Expires: 0");

$m=array();

foreach ($items AS $item)
{
	$k = $item->plan->id.'_'.$item->price;
	
	if (!isset($m[$k])) {
	    $m[$k]=array(
	        'dom'=>$item->plan->building->id,
	        'rooms'=>$item->plan->rooms,
	        'etagy'=>'',
	        'ploshad'=>$item->plan->s_total.'/'.$item->plan->s_living.'/'.$item->plan->s_kitchen,
	        'price'=>$item->price,
	        'skidka'=>'',
	        'spec'=>'',
	    );	    
	}
	
	$m[$k]['etagy'].=$item->floor.', ';
	
	if ($item->hot) {
	   $m[$k]['skidka']='Yes';
	}
	
	if ($item->hot>1) {
	    $m[$k]['spec']=$item->floor;
	}
}

$delimiter =';';

$outputBuffer = fopen("php://output", 'w');

$i=0;
foreach($m as $val) {
    if ($i==0) {
        fputcsv($outputBuffer, array_keys($val), $delimiter);
    }
	fputcsv($outputBuffer, $val, $delimiter);
	$i++;
}
fclose($outputBuffer);

www/protected/views/flats/index.php
<?php
Yii::app()->clientScript->registerScript('hottableexpand','tableExpander("#flatTable",5,"Смотреть все &raquo;"); ');

foreach (Buildings::model()->findAll() as $building) {
    
	$lightbox='lightboxFlats'.$building->id;
	
	Yii::app()->clientScript->registerScript($lightbox,"$(function() {	$('a.".$lightbox."').lightBox(); });");
		
	?>
	<div class="b-dom" id="building<?php echo $building->id;?>">
		<a href="/images/buildings/<?php echo $building->id;?>.png" class="e-img <?php echo $lightbox;?>" style="background-image:url('/images/buildings/s<?php echo $building->id;?>.png'); " title="<?php echo CHtml::encode($building->name.', '.$building->adress);?>"></a>
		<div><span class="e-name"><?php echo $building->name;?></span> <span style="font-size:0.8em;"><?php echo $building->adress;?></span></div>				
		<div style="font-size:0.8em;"><?php echo $building->complTime;?></div>
		<div style="font-size:0.8em;"><?php echo $building->getAttributeLabel('material');?>: <?php echo $building->material;?>; <?php echo $building->getAttributeLabel('floors');?>: <?php echo $building->floors;?></div>
		<!-- 
		<div style="font-size:0.8em;">
			<a href="/images/upload/proektnayadeklaratsia<?php echo $building->id;?>.pdf" title="Проектная декларация на <?php echo CHtml::encode($building->name.', '.$building->adress);?>" target="projectdclr">Проектная декларация</a>
			
			&nbsp; &nbsp; <a href="/images/upload/ddu.pdf" title="Договоры долевого участия <?php echo CHtml::encode($building->name.', '.$building->adress);?>" target="ddu">Договоры долевого участия</a>
			&nbsp; &nbsp; <a href="/images/upload/stroy.pdf" title="Разрешение на строительство <?php echo CHtml::encode($building->name.', '.$building->adress);?>" target="stroi">Разрешение на строительство</a>
					
		</div>
		-->		
	</div>
	
	<table class="b-table_std" id="flatTable" style="margin-bottom:1em;">
	<thead>
	<tr>
	<td></td><td>Этажи</td><td>Общая <br>площадь</td><!-- <td>Площадь<br>квартиры</td>--><td>Жилая</td><td>Кухня</td><td>Лоджия</td><td>Цена</td><td></td><td></td><td></td>
	</tr>
	</thead>
	<tbody>
	<?php	
	$flats=$building->flatsGroup;	
	
	$ctflats=count($flats);
	
	if (!($ctflats>0)) {
		?>
		<tr  class="e-hrow"><td colspan=10 >Квартир в продаже в данный момент нет</td></tr>
		<?php 
	}
	
	$old_rooms=-1;
	foreach ($flats as $flat) {
	    
		$imgTitle=$flat['plan']->name.' в ЖК «Матрешкин двор», '.$building->name.', цена '.TextHelper::price($flat['price']).' руб';
		
		if ($old_rooms<>$flat['plan']->rooms) {
			?>
			</tbody>
			<tbody><tr  class="e-hrow"><td colspan=10 ><?php if ($flat['plan']->rooms>0) { echo $flat['plan']->rooms; ?>-комнатные квартиры<?php } else { ?>Студии<?php } ?></td></tr>
			<?php 
			$old_rooms=$flat['plan']->rooms;
		}
		?>
		<tr>
		  <td><a href="<?php echo $flat['plan']->imgSrc;?>" class="e-grey <?php echo $lightbox;?>" rel="lightbox[plan<?php echo $flat['plan']->id;?>]" title="<?php echo $imgTitle;?>"><?php echo $flat['plan']->name;?></a></td>
		  <td><?php
			
		  	if (count($flat['floors'])>1) {
			  	$floor_l = -999;
				$floor_i = 0;
				
				foreach ($flat['floors'] as $floor) {
					if ($floor <> ($floor_l+1)) {
						if ($floor_i>0) { echo '-'.$floor_l.', '; }
			  			echo $floor;
			  		}
			  		$floor_l = $floor;
			  		$floor_i++;
				}
				
				echo '-'.$floor_l;
		  	} else {		  		
		  		echo array_shift($flat['floors']);
		  	}
		  
		  ?></td>
		  <td><?php echo $flat['plan']->s_total;?> м<sup>2</sup></td>		  
		  <td><?php echo $flat['plan']->s_living;?> м<sup>2</sup></td>
		  <td><?php echo $flat['plan']->s_kitchen;?> м<sup>2</sup></td>
		  <td><?php if ($flat['plan']->s_loggia) { echo $flat['plan']->s_loggia; ?> м<sup>2</sup><?php } elseif ($flat['plan']->loggia) { ?>есть<?php } ?></td>
		  <td><?php echo TextHelper::price($flat['price']);?></td>
		  <td><?php if ($flat['hot']) { ?><a href="<?php echo $this->createUrl('orders/flat',array('flatid'=>$flat['id']));?>" onclick="get_url_to_modal_windows(this.href); return false; " class="b-but" title="Последние квартиры по распродаже!" style="font-weight:normal;">Распродажа!</a><?php } ?></td>
		  <td><a href="<?php echo $flat['plan']->imgSrc;?>" class="e-grey lightbox" title="<?php echo $imgTitle;?>">Планировка</a></td>
		  <td><a href="<?php echo $this->createUrl('orders/flat',array('flatid'=>$flat['id']));?>" class="b-but e-but_grey" onclick="get_url_to_modal_windows(this.href); return false; ">Забронировать!</a></td>
		</tr>
		<?php
	}
	?>
	</tbody>
	</table>
	<?php	
}