www/protected/modules/admin/controllers/FlatsController.php
<?php

class FlatsController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='/layouts/column2';


	public function actionIndex()
	{
		$model=new Flats('search');
		
		$model->unsetAttributes();
		
		if(isset($_GET['Flats'])) { $model->attributes=$_GET['Flats']; }
				
		$this->render('index',array('model'=>$model));
	}
	

	public function actionUpdate($id=0)
	{	
		
		if (!$model=Flats::model()->findByPk($id)) { $model=new Flats; }
				
		if(isset($_POST['Flats']))
		{	
			$model->attributes=$_POST['Flats'];
			
			
			if ($objAddImage=CUploadedFile::getInstance($model,'addImage'))
			{
				$model->addImage=$objAddImage->gettempName();
			}		
								
			if ($model->save()) { $this->redirect(array('flats/index')); }
		}
	
		$this->render('form',array('model'=>$model));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		
		$model=Flats::model()->findByPK($id);		
		$model->delete();
		
		$this->redirect(array('flats/index'));

	}
	
	public function actionImport()
	{
		$model=new FlatsImport;
	
		// if it is ajax validation request
		if(isset($_POST['ajax']) && $_POST['ajax']==='import-form') {
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	
		// collect user input data
		if(isset($_POST['FlatsImport'])) {
			$model->attributes=$_POST['FlatsImport'];
			if ($objFile=CUploadedFile::getInstance($model,'file')) {
				$model->file=$objFile->gettempName();
			}
			// validate user input and redirect to the previous page if valid
			if($model->validate() && $result=$model->load()) {
	
				if (count($result['unknownRows'])>1) {
	
					$this->render('import',array('model'=>$model,'unknownRows'=>$result['unknownRows']));
					return ;
				}
	
				$this->redirect(array('flats/index'));
	
				return ;
			}
	
		}
		 
		$this->render('import',array('model'=>$model,'unknownRows'=>array()));
	}
	/**
	 * Performs the AJAX validation.
	 * @param Section $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='section-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

www/protected/modules/admin/controllers/PlansController.php
<?php

class PlansController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='/layouts/column2';


	public function actionIndex()
	{
		$model=new Plans('search');
		
		$model->unsetAttributes();
		
		if(isset($_GET['Plans'])) { $model->attributes=$_GET['Plans']; }
				
		$this->render('index',array('model'=>$model));
	}
	

	public function actionUpdate($id=0)
	{	
		
		if (!$model=Plans::model()->findByPk($id)) { $model=new Plans; }
				
		if(isset($_POST['Plans']))
		{	
			$model->attributes=$_POST['Plans'];
			
			
			if ($objAddImage=CUploadedFile::getInstance($model,'addImage'))
			{
				$model->addImage=$objAddImage->gettempName();
			}

			
								
			if ($model->save()) { $this->redirect(array('plans/index')); }
			
			
		}
		
		
		
		$this->render('form',array('model'=>$model));
		
	
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		
		$model=Plans::model()->findByPK($id);		
		$model->delete();
		
		$this->redirect(array('plans/index'));

	}
	
	public function actionPlansList($buildingid) {
	
		
		
		$this->renderPartial('_list',array('items'=>Buildings::model()->findByPK($buildingid)->plans,'form'=>Yii::app()->request->getParam('form')));
		
			
		
		
	}
	

	/**
	 * Performs the AJAX validation.
	 * @param Section $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='section-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

www/protected/modules/admin/views/plans/_label.php
<?php
if ($row) { ?>
<label class="e-row">
	<input type="radio" value="<?php echo $row->id;?>" name="<?php echo $form?>[planid]">
	<span><?php echo $row->info;?></span>
	<img src="<?php echo $row->imgSrc;?>" alt="" >	
</label>
<?php
}

www/protected/modules/admin/views/plans/_list.php
<?php
if ($items)
{
	?>
	<div class="b-plans">
	<?php 
	foreach ($items as $row)
	{
		$this->renderPartial('_label',array('row'=>$row,'form'=>$form));
	}
	?>
	<div class=clear></div>
	</div>
<?php
}

www/protected/modules/admin/views/plans/form.php
<?php
	if ($model->id>0)	{ $tit='Редактирование планировки'; }
	else				{ $tit='Добавить планировку'; }
	
	
	$this->breadcrumbs=array(
		'Разделы сайта'=>array('section/'),
		'Планировки'=>array('plans/index'),
		$tit
	);
	
	$this->menu=array(
			array('label'=>'Планировки', 			'url'=>array('plans/index')),
			array('label'=>'Добавить планировку',	'url'=>array('plans/update')),
			array('label'=>'Квартиры', 				'url'=>array('flats/index')),			
			array('label'=>'Добавить квартиру', 	'url'=>array('flats/update')),
	        array('label'=>'Импорт', 	            'url'=>array('flats/import')),
	);
?>

<h1><?php echo $tit;?></h1>

<div class="b-form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'foto-form',
	'htmlOptions'=>array('enctype'=>'multipart/form-data'),
	'enableAjaxValidation'=>false,
	
)); 

	 echo $form->hiddenField($model,'id');

	 echo $form->errorSummary($model); ?>

	
	<div class="row">
		<?php echo $form->labelEx($model,'buildingid'); ?>
		<?php echo $form->dropDownList($model,'buildingid',CHtml::listData(Buildings::model()->findAll(),'id','name') ); ?>
		<?php echo $form->error($model,'buildingid'); ?>
	</div>
	
	<div class="row">
		<?php echo $form->labelEx($model,'rooms'); ?>
		<?php echo $form->textField($model,'rooms'); ?>
		<?php echo $form->error($model,'rooms'); ?>
	</div>
	
	<div class="row">
		<?php echo $form->labelEx($model,'s_total'); ?>
		<?php echo $form->textField($model,'s_total'); ?>
		<?php echo $form->error($model,'s_total'); ?>
	</div>
	
	<div class="row">
		<?php echo $form->labelEx($model,'s_living'); ?>
		<?php echo $form->textField($model,'s_living'); ?>
		<?php echo $form->error($model,'s_living'); ?>
	</div>
	
	<div class="row">
		<?php echo $form->labelEx($model,'s_kitchen'); ?>
		<?php echo $form->textField($model,'s_kitchen'); ?>
		<?php echo $form->error($model,'s_kitchen'); ?>
	</div>
	
	<div class="row">
		<?php echo $form->labelEx($model,'loggia'); ?>
		<?php echo $form->checkBox($model,'loggia'); ?>
		<?php echo $form->error($model,'loggia'); ?>
	</div>
	
	<div class="row">
		<?php echo $form->labelEx($model,'s_loggia'); ?>
		<?php echo $form->textField($model,'s_loggia'); ?>
		<?php echo $form->error($model,'s_loggia'); ?>
	</div>

	<div class="row">
        <?php echo $form->labelEx($model,'addImage'); ?>        
        <?php echo $form->fileField($model,'addImage'); ?>
        <?php echo $form->error($model,'addImage'); ?>
    </div>

	 <div class="row">
		<?php echo $form->labelEx($model,'tekst'); ?>
		<?php echo $form->textField($model,'tekst'); ?>
		<?php echo $form->error($model,'tekst'); ?>
	</div>

	<div class="row buttons" style="margin-top:20px;">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Создать' : 'Сохранить'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->


<?php
if ($model->id>0)
{
	?>
	<h3>Изображение</h3>
	<img src="<?php echo $model->imgSrc;?>" alt="" style="max-width:100%;">
	<?php
	
}

www/protected/modules/admin/views/plans/index.php
<?php

$this->breadcrumbs=array(
		'Разделы сайта'=>array('section/'),
		'Планировки'
);

$this->menu=array(
			array('label'=>'Планировки', 			'url'=>array('plans/index')),
			array('label'=>'Добавить планировку',	'url'=>array('plans/update')),
			array('label'=>'Квартиры', 				'url'=>array('flats/index')),			
			array('label'=>'Добавить квартиру', 	'url'=>array('flats/update')),
            array('label'=>'Импорт', 	            'url'=>array('flats/import')),
);

?>
<h1>Планировки</h1>
<?php 

//каталог
$this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'catalog-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		
		'id',
		
		array(
			'name'=>'buildingid',
			'value'=>'$data->building->name',
			'filter'=>CHtml::listData(Buildings::model()->findAll(),'id','name'),
			 'htmlOptions'=>array('width'=>'50px'),
		),
			
	

		array(
			'name'=>'ImgPreviewHtml',
					
			'type'=>'html',	
			'filter'=>false,		
		),

		'rooms',
		
		's_total',
		
		's_living',
		
		's_kitchen',
		
		's_loggia',
		
		'loggia',
		
		array(
			'class'=>'CButtonColumn',
			'template'=>'{update} {delete}',
			
		),
	),
));