www/protected/models/User.php
<?php
class User extends CActiveRecord
{
	/**
	 * Returns the static model of the specified AR class.
	 * @return User the static model class
	 */
	
	public $password_new;
	public $password_confirm;
	
	
	
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return '{{user}}';
	}

	public function defaultScope(){
		return array(
				'order'=>'role ASC, id DESC'
		);
	}
	
	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('email, name, tel, city', 'required'),			
			array('email, tel, city', 'length', 'max'=>255),				
			array('email', 'email','message'=>'E-mail некорректный'),
			array('email', 'unique', 'message' => 'Указанный email уже зарегистрирован'),
			array('tel','filter','filter'=>array('TextHelper','phone')),
			array('tel', 'unique', 'message' => 'Указанный телефон уже зарегистрирован'),
						
			array('password_new','required','on'=>array('create')),
			array('password_new', 'length', 'min'=>1),
			array('password_confirm', 'compare', 'compareAttribute'=>'password_new', 'message'=>'Пароли не совпадают'),
			
						
			array('restore', 'length', 'max'=>255,'on'=>array('restore')),			
			
						
			array('role', 'length', 'max'=>10),
			array('address', 'safe'),
			
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			//array('id, email, name, tel', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'id',			
			'email' => 'E-mail',
			'name' => 'Ваше фамилия и имя',
			'tel' => 'Номер телефона',			
			'city'=>'Город',
			'address'=>'Адрес',
			'password_new'=>'Пароль',
			'password_confirm'=>'Повторите пароль',			
		);
	}
	
	public static function getRoleList()
	{		
		return array('user'=>'Пользователь','admin'=>'Администратор');
	}
	
	public function getRoleName()
	{
		$m=$this->getRoleList();
		
		return $m[$this->role];
	}
	
	
	
	
		/**
	 * Checks if the given password is correct.
	 * @param string the password to be validated
	 * @return boolean whether the password is valid
	 */
	
	protected function beforeSave()
    {
     	//проверям можем ли мы менять роль изера
    	if (!Yii::app()->user->checkAccess('changeUserRole')) { unset($this->role); }
        
        if($this->password_new) { $this->password = $this->hashPassword($this->password_new); }

        return true;
    }
	
	protected function afterSave()
	{
		//востановление пароля письмо
		if ($this->getScenario()=='restore' AND $this->restore<>'')
		{			
			$subject = 'Восстановление пароля на сайте '.Yii::app()->name;
			$mailheaders = "Content-type:text/html;charset=utf-8\r\n";
			$mailheaders .= "From: ".Yii::app()->params['email']."\r\n";
				
			$txt=Yii::app()->controller->renderPartial('application.views.user.restoreMsg',array('model'=>$this), true);
							
			mail($this->email, $subject, $txt, $mailheaders);
			
		}
	}
	


	public function validatePassword($password)
    {
        return CPasswordHelper::verifyPassword($password,$this->password);
    }
 
    public function hashPassword($password)
    {
        return CPasswordHelper::hashPassword($password);
    }

    
    public function search()
    {
    	$criteria=new CDbCriteria;
    
    	$criteria->compare('id',$this->id);    
    	$criteria->compare('name',$this->name,true);
    	$criteria->compare('tel',$this->tel,true);
    	$criteria->compare('email',$this->email,true);
    	$criteria->compare('role',$this->role);
    	
    
    	return new CActiveDataProvider($this, array(
    			'criteria'=>$criteria,
    			'pagination'    => array('pageSize'  => 100)
    	));
    }
}

www/protected/controllers/UserController.php
<?php

class UserController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='/layouts/default';
	
	
	
	
	public function actionIndex()
	{
		
		$user=User::model()->findByPk(Yii::app()->user->id);
		
		if (!($user->id>0))
		{
			$this->redirect(array('user/login'));
		}		
		
	}


	public function actionLogin()
	{
		if (Yii::app()->user->id>0)  { $this->redirect(array('user/index')); }
		
		
		
		$model=new LoginForm;

		// if it is ajax validation request
		if(isset($_POST['ajax']) && $_POST['ajax']==='login-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}

		// collect user input data
		if(isset($_POST['LoginForm']))
		{
			$model->attributes=$_POST['LoginForm'];
			// validate user input and redirect to the previous page if valid
			if($model->validate() && $model->login()) {
			    $this->redirect('/admin');
			    //$this->redirect(Yii::app()->request->urlReferrer);
			}
				
		}
		
		// display the login form
		if (Yii::app()->request->isAjaxRequest) 
		{
        	$this->renderPartial('login',array('model'=>$model));
		} else {			
			$this->render('login',array('model'=>$model));
		}
		
		
	}

	/**
	 * Logs out the current user and redirect to homepage.
	 */
	public function actionLogout()
	{
		Yii::app()->user->logout();
		$this->redirect(Yii::app()->request->urlReferrer);
	}
	
	
	
	
	public function actionRestore()
	{
		if (Yii::app()->user->id>0)  { $this->redirect(array('user/index')); }
		
		$model=new RestorePassForm;
		
		$this->h1='Восстановление пароля';
		
		
		//если пришли данные о востановлении
		if (isset($_GET['hash']))
		{
			$model->attributes=array('userid'=>$_GET['id'],'hash'=>$_GET['hash']);
			if ($model->login())
			{
				$this->redirect(array('user/profile'));
			}
		}
		
		//если запрос на восстановление пароля
		if (isset($_POST['RestorePassForm']))
		{
			$model->attributes=$_POST['RestorePassForm'];			
			if ($model->request())
			{
				$this->render('restoreSent', array('model'=>$model));
				return ;
			}
		}
		
		
		$this->render('restore', array('model'=>$model));
		
		
	}
	
}

www/protected/views/user/index.php
<?php 
$this->h1='Личный кабинет';
//$this->breadcrumbs=array('Редактировать информацию'=>array('user/profile'));

?>

<div class="b-user_info">
	<p><strong><?php echo $user->name;?></strong> (<a href="<?php echo $this->createUrl('user/profile');?>">редактировать</a>)</p>	
	<p><?php echo $user->city;?>, <?php echo $user->address;?>, тел.: <?php echo $user->tel;?>, e-mail: <?php echo $user->email;?></p>
</div>


<?php
$itemsBasket=Basket::get();
if (count($itemsBasket)>0)
{
	?>
	<div style="margin-bottom:60px; padding-bottom:50px; border-bottom:1px solid #999999;">
	<?php
	$this->renderPartial('//basket/index',array('items'=>$itemsBasket));
	?>
	</div>
	<?php
}
?>

<h2>История заказов</h2>
<?php
$orders=$user->orders;

if (count($orders)>0)
{
	?>
	<table class="b-table_std">
	<thead>
	<tr>
	  <td>Номер заказа</td>
	  <td>Дата заказа</td>
	  <td>Кол-во</td>
	  <td>Сумма заказа</td>
	  <td>Статус</td>		  
	</tr>
	</thead>
	<?php
	
	foreach ($orders as $order)
	{
		?>
		<tr>
		  <td><a href="<?php echo $this->createUrl('orders/item',array('id'=>$order->id));?>">ID <?php echo $order->id;?></a></td>
		  <td><?php echo date('d.m.Y',$order->date);?></td>
		  <td><?php echo $order->count;?> шт.</td>
		  <td><?php echo TextHelper::price($order->price);?> руб.</td>
		  <td><?php echo $order->statusName;?></td>		
		  
		</tr>
		<?php
	}
	
	?>
	</table>
	<?php
}
else
{
	?><p>Заказов пока нет</p><?php
}

	

www/protected/views/user/login.php
<p style="float:right; margin-top:14px;"><a href="<?php echo $this->createUrl('user/profile');?>" onclick="get_url_to_modal_windows(this.href); return false;">Регистрация</a></p>

<h1>Вход</h1>





<div class="b-form" style="width:250px;">
<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'login-form',
	'enableClientValidation'=>true,
	'clientOptions'=>array(
		'validateOnSubmit'=>true,
	),
)); ?>


	<div class="e-row">
		<?php echo $form->labelEx($model,'email'); ?>
		<?php echo $form->textField($model,'email'); ?>
		<?php echo $form->error($model,'email'); ?>
	</div>

	<div class="e-row">
		<?php echo $form->labelEx($model,'password'); ?>
		<?php echo $form->passwordField($model,'password'); ?>
		<?php echo $form->error($model,'password'); ?>		
	</div>

	<div class="e-row rememberMe">
		<?php echo $form->checkBox($model,'rememberMe'); ?>
		<?php echo $form->label($model,'rememberMe'); ?>
		<?php echo $form->error($model,'rememberMe'); ?>
	</div>
	
	<p><a href="<?php echo $this->createUrl('user/restore');?>">Забыли пароль?</a></p>

	<div class="e-row buttons">
		<?php echo CHtml::submitButton('Login'); ?>
	</div>

<?php $this->endWidget(); ?>
</div><!-- form -->

www/protected/views/user/profile.php
<?php 
if ($model->id>0)
{
	$tit='Ваш профиль';
	$submt='Сохранить';
}
else
{
	$tit='Информация о покупателе';
	$submt='Регистрация';
}


if ($this->layout=='/user/layouts/basket')
{
	$tit='';
	$submt='';
}

if ($tit) { echo '<h1>'.$tit.'</h1>'; }

?>

<div class="b-form" style="width:250px;">

<?php 

	
	$form=$this->beginWidget('CActiveForm', array(
		'id'=>'user-form',
		'enableAjaxValidation'=>true,	
		'clientOptions'=>array('validateOnSubmit'=>true,),
		)
	);

?>

	<!--
	<p class="note">Поля помечанные <span class="required">*</span> обязательны.</p>
	-->
	
	
	
	<div class="e-row">
	<?php echo $form->labelEx($model,'email'); ?>
	<?php echo $form->textField($model,'email'); ?>
	<?php echo $form->error($model,'email'); ?>
	</div>
	
	
	<div class="e-row">
	<?php echo $form->labelEx($model,'password_new'); ?>
	<?php echo $form->passwordField($model,'password_new'); ?>
	<?php echo $form->error($model,'password_new'); ?>
	
	</div>
	
	<div class="e-row">
	<?php echo $form->labelEx($model,'password_confirm'); ?>
	<?php echo $form->passwordField($model,'password_confirm'); ?>
	<?php echo $form->error($model,'password_confirm'); ?>
	</div>
	
	
	<div class="e-row">
	<?php echo $form->labelEx($model,'name'); ?>
	<?php echo $form->textField($model,'name'); ?>
	<?php echo $form->error($model,'name'); ?>
	</div>
	
	<div class="e-row">
	<?php echo $form->labelEx($model,'tel'); ?>
	<?php echo $form->textField($model,'tel'); ?>
	<?php echo $form->error($model,'tel'); ?>
	</div>
	
	<div class="e-row">
	<?php echo $form->labelEx($model,'city'); ?>
	<?php echo $form->textField($model,'city'); ?>
	<?php echo $form->error($model,'city'); ?>
	</div>
	
	<div class="e-row">
	<?php echo $form->labelEx($model,'address'); ?>
	<?php echo $form->textField($model,'address'); ?>
	<?php echo $form->error($model,'address'); ?>
	</div>
	

	<?php 
	if ($submt)
	{	
	?>
	<div class="e-row submit">
		<?php echo CHtml::submitButton($submt); ?>
	</div>
	<?php 
	}
	?>

<?php $this->endWidget(); ?>
</div>

www/protected/views/user/restore.php
<?php
$this->h1='';
?>

<p style="float:right; margin-top:14px;"><a href="<?php echo $this->createUrl('user/profile');?>" onclick="get_url_to_modal_windows(this.href); return false;">Регистрация</a></p>

<h1>Восстановление пароля</h1>

<div class="b-form" style="width:250px;">
<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'login-form',
	'enableClientValidation'=>true,
	'clientOptions'=>array(
		'validateOnSubmit'=>true,
	),
)); ?>


	<div class="e-row">
		<?php echo $form->labelEx($model,'email'); ?>
		<?php echo $form->textField($model,'email'); ?>
		<?php echo $form->error($model,'email'); ?>
	</div>

	

	<div class="e-row buttons">
		<?php echo CHtml::submitButton('Восстановить'); ?>
	</div>

<?php $this->endWidget(); ?>
</div><!-- form -->

www/protected/views/user/restoreMsg.php
<p>На нашем сайты был запрос на востановление вашего пароля</p>
<p>Пройдите по ссылке для восстановления вашего пароля <a href="<?php echo $this->createAbsoluteUrl('user/restore',array('id'=>$model->id,'hash'=>$model->restore));?>"><?php echo $this->createAbsoluteUrl('user/restore',array('id'=>$model->id,'hash'=>$model->restore));?></a></p>

www/protected/views/user/restoreSent.php
<p>На указанный email отправлена инструкция по восстановлению пароля</p>